# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agi.proto_gen import erisml_pb2 as erisml__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in erisml_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ErisMLServiceStub(object):
    """---------------------------------------------------------------------------
    ErisML Service Definition
    ---------------------------------------------------------------------------

    ErisMLService provides ethical evaluation for AGI-HPC cognitive architecture.
    Integrates with the Safety Gateway for pre-action safety checks.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateStep = channel.unary_unary(
                '/agi.erisml.v1.ErisMLService/EvaluateStep',
                request_serializer=erisml__pb2.EvaluateStepRequest.SerializeToString,
                response_deserializer=erisml__pb2.EvaluateStepResponse.FromString,
                _registered_method=True)
        self.EvaluatePlan = channel.unary_unary(
                '/agi.erisml.v1.ErisMLService/EvaluatePlan',
                request_serializer=erisml__pb2.EvaluatePlanRequest.SerializeToString,
                response_deserializer=erisml__pb2.EvaluatePlanResponse.FromString,
                _registered_method=True)
        self.ComputeBondIndex = channel.unary_unary(
                '/agi.erisml.v1.ErisMLService/ComputeBondIndex',
                request_serializer=erisml__pb2.BondIndexRequest.SerializeToString,
                response_deserializer=erisml__pb2.BondIndexResultProto.FromString,
                _registered_method=True)
        self.VerifyHohfeldian = channel.unary_unary(
                '/agi.erisml.v1.ErisMLService/VerifyHohfeldian',
                request_serializer=erisml__pb2.HohfeldianRequest.SerializeToString,
                response_deserializer=erisml__pb2.HohfeldianResponse.FromString,
                _registered_method=True)


class ErisMLServiceServicer(object):
    """---------------------------------------------------------------------------
    ErisML Service Definition
    ---------------------------------------------------------------------------

    ErisMLService provides ethical evaluation for AGI-HPC cognitive architecture.
    Integrates with the Safety Gateway for pre-action safety checks.
    """

    def EvaluateStep(self, request, context):
        """Evaluate a single plan step through DEME pipeline
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluatePlan(self, request, context):
        """Evaluate entire plan graph with aggregated Bond Index
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeBondIndex(self, request, context):
        """Compute Bond Index for Hohfeldian position pairs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyHohfeldian(self, request, context):
        """Verify Hohfeldian correlative symmetry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ErisMLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateStep': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateStep,
                    request_deserializer=erisml__pb2.EvaluateStepRequest.FromString,
                    response_serializer=erisml__pb2.EvaluateStepResponse.SerializeToString,
            ),
            'EvaluatePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluatePlan,
                    request_deserializer=erisml__pb2.EvaluatePlanRequest.FromString,
                    response_serializer=erisml__pb2.EvaluatePlanResponse.SerializeToString,
            ),
            'ComputeBondIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeBondIndex,
                    request_deserializer=erisml__pb2.BondIndexRequest.FromString,
                    response_serializer=erisml__pb2.BondIndexResultProto.SerializeToString,
            ),
            'VerifyHohfeldian': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyHohfeldian,
                    request_deserializer=erisml__pb2.HohfeldianRequest.FromString,
                    response_serializer=erisml__pb2.HohfeldianResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agi.erisml.v1.ErisMLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agi.erisml.v1.ErisMLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ErisMLService(object):
    """---------------------------------------------------------------------------
    ErisML Service Definition
    ---------------------------------------------------------------------------

    ErisMLService provides ethical evaluation for AGI-HPC cognitive architecture.
    Integrates with the Safety Gateway for pre-action safety checks.
    """

    @staticmethod
    def EvaluateStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agi.erisml.v1.ErisMLService/EvaluateStep',
            erisml__pb2.EvaluateStepRequest.SerializeToString,
            erisml__pb2.EvaluateStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluatePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agi.erisml.v1.ErisMLService/EvaluatePlan',
            erisml__pb2.EvaluatePlanRequest.SerializeToString,
            erisml__pb2.EvaluatePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeBondIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agi.erisml.v1.ErisMLService/ComputeBondIndex',
            erisml__pb2.BondIndexRequest.SerializeToString,
            erisml__pb2.BondIndexResultProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyHohfeldian(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agi.erisml.v1.ErisMLService/VerifyHohfeldian',
            erisml__pb2.HohfeldianRequest.SerializeToString,
            erisml__pb2.HohfeldianResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
